import ReactQuery from "@/components/reactQuery";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./theme/themeRegistry";
import { ReactNode } from "react";
import { Session } from "next-auth";
import NextAuthProvider from "@/components/nextAuthProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "belajar",
  description: "Generated by create next app",
};
interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <NextAuthProvider session={session}>
         
            <ReactQuery>{children}</ReactQuery>
          
        </NextAuthProvider>
      </body>
    </html>
  );
}
